Formatting date according to different locale
payfunc/tidily pull request #54
Opened 2021-12-02 16:10 UTC by qijieye

It's a new way to format date. According to previous way, we restrict input by `state.value.length < 10 && ((symbol >= "0" && symbol <= "9") || symbol == "-" `, then using regex to format date after input. The new solution is to reinforce the restriction in every digit of certain position before input, reducing the usage of regex. For example, the first digit of day must be smaller than 4 and if the first digit of day is 3, the second digit only accept 0 or 1.  We continue to use  `function daysPerMonth ` to regulate the last day of each month.

2021-12-06 10:51 UTC, Magnus93 commented on DateFormat.ts
> +export type DateFormat = "YYYY-MM-dd" | "dd/MM/YYYY"
Is there a reason `d` is lowercase while `M` and `Y` is uppercase?

2021-12-06 10:55 UTC, Magnus93 commented on DateFormat.ts
> +		return typeof value == "string" && (value == "YYYY-MM-dd" || value == "dd/MM/YYYY")
Break `DateFormat` into own file, so you can add `DateFormat.is` function

2021-12-06 12:02 UTC, Magnus93 commented on Handler/date/helper.ts
> +				validYear(symbol, state, 10, 6)
If I understand correctly `firstDigit` and `secondDigit` are indices. Shouldn't it be `validYear(symbol, state, 6, 10)`?
Also maybe rename `firstDigit`->`startIndex` and `secondDigit`->`endIndex`?

2021-12-06 12:06 UTC, Magnus93 commented on Handler/date/index.ts
> +				result = validFormat(symbol, state, "dd/MM/YYYY")
You can remove the switch and only set
``` ts
result = validFormat(symbol, state, this.formatting ?? "YYYY-MM-dd")
```

2021-12-16 14:26 UTC, qijieye commented
Added more formats, now it supports dd/mm/YYYY, mm/dd/YYYY(en-US), YYYY-mm-dd, dd.mm.YYYY
Just a demo
![Screenshot from 2021-12-16 09-49-13](https://user-images.githubusercontent.com/86956109/146389865-a8841cba-50b3-4591-ae5c-10485301db4d.png)

2021-12-16 14:45 UTC, Magnus93 commented on DateFormat.ts
> +			default:
I generally put the default statement last. This will still work, but may be less consistent with other switch statements in the code.

2021-12-17 12:58 UTC, Magnus93 requested changes
Change english.spec and us.spec to "en-GB.spec.ts" and "en-US.spec.ts" for consistency

2021-12-17 13:16 UTC, Magnus93 approved these changes, later dismissed

2021-12-17 13:50 UTC, nilssonemma submitted a review, later dismissed

2021-12-17 17:44 UTC, Magnus93 approved these changes, later dismissed

2021-12-20 08:33 UTC, nilssonemma approved these changes, later dismissed

2021-12-22 13:14 UTC, Magnus93 approved these changes, later dismissed

2021-12-22 13:15 UTC, marcushanses submitted a review, later dismissed

2021-12-23 07:51 UTC, Magnus93 approved these changes

2022-01-04 10:14 UTC, merged