Fix locales for Date
payfunc/tidily pull request #55
Opened 2021-12-21 13:21 UTC by Magnus93

2021-12-21 13:28 UTC, nilssonemma commented on Handler/date/helper.ts
> +export function validDay(symbol: string, state: Readonly<State>, startIndex: number, endIndex: number): boolean {
Please only have 1 return statement per function. Use a result variable instead

2021-12-21 13:34 UTC, robinnedergard submitted a review, later dismissed

2021-12-21 13:37 UTC, Magnus93 commented on Handler/date/helper.ts
> +export function validDay(symbol: string, state: Readonly<State>, startIndex: number, endIndex: number): boolean {
Fixed

2021-12-21 13:39 UTC, nilssonemma approved these changes, later dismissed

2021-12-21 13:39 UTC, robinnedergard requested changes

2021-12-21 13:39 UTC, robinnedergard commented on Handler/date/index.ts
> +			return year && month && day ? day > 0 && daysPerMonth(year, month) >= day : false
one return per function

2021-12-21 13:42 UTC, Magnus93 commented on Handler/date/index.ts
> +			return year && month && day ? day > 0 && daysPerMonth(year, month) >= day : false
Fixat

2021-12-21 13:46 UTC, robinnedergard requested changes

2021-12-21 13:46 UTC, robinnedergard commented on Handler/date/index.ts
> +	return unformated
Like this?:
```suggestion
	return result
```

2021-12-21 13:47 UTC, robinnedergard approved these changes

2021-12-21 13:47 UTC, nilssonemma approved these changes

2021-12-21 13:48 UTC, Magnus93 commented on Handler/date/index.ts
> +	return unformated
Fixed

2021-12-22 06:03 UTC, fredrikbryntesson approved these changes

2021-12-22 06:03 UTC, merged